#!/bin/sh

NAME=firehol-update-ipsets
IMAGE=firehol-update-ipsets
USER=firehol-update-ipsets
USER_DIR=./user-dir

podman run \
    --rm -it \
    --name "${NAME}" \
    --log-driver=none \
    --uidmap 0:100000:65536 \
    --gidmap 0:100000:65536 \
    --no-hosts \
    --mount="type=bind,src=${USER_DIR},target=/home/${USER}" \
    "${IMAGE}" \
    "$@"
